name: Continuous Integration

on:
  pull_request:
    branches: [main] # run on PRs opened against `main`

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [16]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check Node Version
        run: node --version

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: TypeScript Compilation
        run: yarn type-check

      - name: Lint
        run: yarn lint
